// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `steamdatagram_auth_messages.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct CMsgSteamDatagramRelayAuthTicket {
    // message fields
    time_expiry: ::std::option::Option<u32>,
    authorized_steam_id: ::std::option::Option<u64>,
    authorized_public_ip: ::std::option::Option<u32>,
    gameserver_steam_id: ::std::option::Option<u64>,
    gameserver_net_id: ::std::option::Option<u64>,
    legacy_signature: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    app_id: ::std::option::Option<u32>,
    gameserver_pop_id: ::std::option::Option<u32>,
    virtual_port: ::std::option::Option<u32>,
    pub extra_fields: ::protobuf::RepeatedField<CMsgSteamDatagramRelayAuthTicket_ExtraField>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CMsgSteamDatagramRelayAuthTicket {
    fn default() -> &'a CMsgSteamDatagramRelayAuthTicket {
        <CMsgSteamDatagramRelayAuthTicket as ::protobuf::Message>::default_instance()
    }
}

impl CMsgSteamDatagramRelayAuthTicket {
    pub fn new() -> CMsgSteamDatagramRelayAuthTicket {
        ::std::default::Default::default()
    }

    // optional fixed32 time_expiry = 1;


    pub fn get_time_expiry(&self) -> u32 {
        self.time_expiry.unwrap_or(0)
    }
    pub fn clear_time_expiry(&mut self) {
        self.time_expiry = ::std::option::Option::None;
    }

    pub fn has_time_expiry(&self) -> bool {
        self.time_expiry.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_expiry(&mut self, v: u32) {
        self.time_expiry = ::std::option::Option::Some(v);
    }

    // optional fixed64 authorized_steam_id = 2;


    pub fn get_authorized_steam_id(&self) -> u64 {
        self.authorized_steam_id.unwrap_or(0)
    }
    pub fn clear_authorized_steam_id(&mut self) {
        self.authorized_steam_id = ::std::option::Option::None;
    }

    pub fn has_authorized_steam_id(&self) -> bool {
        self.authorized_steam_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_authorized_steam_id(&mut self, v: u64) {
        self.authorized_steam_id = ::std::option::Option::Some(v);
    }

    // optional fixed32 authorized_public_ip = 3;


    pub fn get_authorized_public_ip(&self) -> u32 {
        self.authorized_public_ip.unwrap_or(0)
    }
    pub fn clear_authorized_public_ip(&mut self) {
        self.authorized_public_ip = ::std::option::Option::None;
    }

    pub fn has_authorized_public_ip(&self) -> bool {
        self.authorized_public_ip.is_some()
    }

    // Param is passed by value, moved
    pub fn set_authorized_public_ip(&mut self, v: u32) {
        self.authorized_public_ip = ::std::option::Option::Some(v);
    }

    // optional fixed64 gameserver_steam_id = 4;


    pub fn get_gameserver_steam_id(&self) -> u64 {
        self.gameserver_steam_id.unwrap_or(0)
    }
    pub fn clear_gameserver_steam_id(&mut self) {
        self.gameserver_steam_id = ::std::option::Option::None;
    }

    pub fn has_gameserver_steam_id(&self) -> bool {
        self.gameserver_steam_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_gameserver_steam_id(&mut self, v: u64) {
        self.gameserver_steam_id = ::std::option::Option::Some(v);
    }

    // optional fixed64 gameserver_net_id = 5;


    pub fn get_gameserver_net_id(&self) -> u64 {
        self.gameserver_net_id.unwrap_or(0)
    }
    pub fn clear_gameserver_net_id(&mut self) {
        self.gameserver_net_id = ::std::option::Option::None;
    }

    pub fn has_gameserver_net_id(&self) -> bool {
        self.gameserver_net_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_gameserver_net_id(&mut self, v: u64) {
        self.gameserver_net_id = ::std::option::Option::Some(v);
    }

    // optional bytes legacy_signature = 6;


    pub fn get_legacy_signature(&self) -> &[u8] {
        match self.legacy_signature.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_legacy_signature(&mut self) {
        self.legacy_signature.clear();
    }

    pub fn has_legacy_signature(&self) -> bool {
        self.legacy_signature.is_some()
    }

    // Param is passed by value, moved
    pub fn set_legacy_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.legacy_signature = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_legacy_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.legacy_signature.is_none() {
            self.legacy_signature.set_default();
        }
        self.legacy_signature.as_mut().unwrap()
    }

    // Take field
    pub fn take_legacy_signature(&mut self) -> ::std::vec::Vec<u8> {
        self.legacy_signature.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional uint32 app_id = 7;


    pub fn get_app_id(&self) -> u32 {
        self.app_id.unwrap_or(0)
    }
    pub fn clear_app_id(&mut self) {
        self.app_id = ::std::option::Option::None;
    }

    pub fn has_app_id(&self) -> bool {
        self.app_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_app_id(&mut self, v: u32) {
        self.app_id = ::std::option::Option::Some(v);
    }

    // optional fixed32 gameserver_pop_id = 9;


    pub fn get_gameserver_pop_id(&self) -> u32 {
        self.gameserver_pop_id.unwrap_or(0)
    }
    pub fn clear_gameserver_pop_id(&mut self) {
        self.gameserver_pop_id = ::std::option::Option::None;
    }

    pub fn has_gameserver_pop_id(&self) -> bool {
        self.gameserver_pop_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_gameserver_pop_id(&mut self, v: u32) {
        self.gameserver_pop_id = ::std::option::Option::Some(v);
    }

    // optional uint32 virtual_port = 10;


    pub fn get_virtual_port(&self) -> u32 {
        self.virtual_port.unwrap_or(0)
    }
    pub fn clear_virtual_port(&mut self) {
        self.virtual_port = ::std::option::Option::None;
    }

    pub fn has_virtual_port(&self) -> bool {
        self.virtual_port.is_some()
    }

    // Param is passed by value, moved
    pub fn set_virtual_port(&mut self, v: u32) {
        self.virtual_port = ::std::option::Option::Some(v);
    }

    // repeated .CMsgSteamDatagramRelayAuthTicket.ExtraField extra_fields = 8;


    pub fn get_extra_fields(&self) -> &[CMsgSteamDatagramRelayAuthTicket_ExtraField] {
        &self.extra_fields
    }
    pub fn clear_extra_fields(&mut self) {
        self.extra_fields.clear();
    }

    // Param is passed by value, moved
    pub fn set_extra_fields(&mut self, v: ::protobuf::RepeatedField<CMsgSteamDatagramRelayAuthTicket_ExtraField>) {
        self.extra_fields = v;
    }

    // Mutable pointer to the field.
    pub fn mut_extra_fields(&mut self) -> &mut ::protobuf::RepeatedField<CMsgSteamDatagramRelayAuthTicket_ExtraField> {
        &mut self.extra_fields
    }

    // Take field
    pub fn take_extra_fields(&mut self) -> ::protobuf::RepeatedField<CMsgSteamDatagramRelayAuthTicket_ExtraField> {
        ::std::mem::replace(&mut self.extra_fields, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for CMsgSteamDatagramRelayAuthTicket {
    fn is_initialized(&self) -> bool {
        for v in &self.extra_fields {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed32()?;
                    self.time_expiry = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.authorized_steam_id = ::std::option::Option::Some(tmp);
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed32()?;
                    self.authorized_public_ip = ::std::option::Option::Some(tmp);
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.gameserver_steam_id = ::std::option::Option::Some(tmp);
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.gameserver_net_id = ::std::option::Option::Some(tmp);
                },
                6 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.legacy_signature)?;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.app_id = ::std::option::Option::Some(tmp);
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed32()?;
                    self.gameserver_pop_id = ::std::option::Option::Some(tmp);
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.virtual_port = ::std::option::Option::Some(tmp);
                },
                8 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.extra_fields)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.time_expiry {
            my_size += 5;
        }
        if let Some(v) = self.authorized_steam_id {
            my_size += 9;
        }
        if let Some(v) = self.authorized_public_ip {
            my_size += 5;
        }
        if let Some(v) = self.gameserver_steam_id {
            my_size += 9;
        }
        if let Some(v) = self.gameserver_net_id {
            my_size += 9;
        }
        if let Some(ref v) = self.legacy_signature.as_ref() {
            my_size += ::protobuf::rt::bytes_size(6, &v);
        }
        if let Some(v) = self.app_id {
            my_size += ::protobuf::rt::value_size(7, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.gameserver_pop_id {
            my_size += 5;
        }
        if let Some(v) = self.virtual_port {
            my_size += ::protobuf::rt::value_size(10, v, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.extra_fields {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.time_expiry {
            os.write_fixed32(1, v)?;
        }
        if let Some(v) = self.authorized_steam_id {
            os.write_fixed64(2, v)?;
        }
        if let Some(v) = self.authorized_public_ip {
            os.write_fixed32(3, v)?;
        }
        if let Some(v) = self.gameserver_steam_id {
            os.write_fixed64(4, v)?;
        }
        if let Some(v) = self.gameserver_net_id {
            os.write_fixed64(5, v)?;
        }
        if let Some(ref v) = self.legacy_signature.as_ref() {
            os.write_bytes(6, &v)?;
        }
        if let Some(v) = self.app_id {
            os.write_uint32(7, v)?;
        }
        if let Some(v) = self.gameserver_pop_id {
            os.write_fixed32(9, v)?;
        }
        if let Some(v) = self.virtual_port {
            os.write_uint32(10, v)?;
        }
        for v in &self.extra_fields {
            os.write_tag(8, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CMsgSteamDatagramRelayAuthTicket {
        CMsgSteamDatagramRelayAuthTicket::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "time_expiry",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.time_expiry },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.time_expiry },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "authorized_steam_id",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.authorized_steam_id },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.authorized_steam_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "authorized_public_ip",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.authorized_public_ip },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.authorized_public_ip },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "gameserver_steam_id",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.gameserver_steam_id },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.gameserver_steam_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "gameserver_net_id",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.gameserver_net_id },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.gameserver_net_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "legacy_signature",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.legacy_signature },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.legacy_signature },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "app_id",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.app_id },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.app_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "gameserver_pop_id",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.gameserver_pop_id },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.gameserver_pop_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "virtual_port",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.virtual_port },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.virtual_port },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<CMsgSteamDatagramRelayAuthTicket_ExtraField>>(
                "extra_fields",
                |m: &CMsgSteamDatagramRelayAuthTicket| { &m.extra_fields },
                |m: &mut CMsgSteamDatagramRelayAuthTicket| { &mut m.extra_fields },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CMsgSteamDatagramRelayAuthTicket>(
                "CMsgSteamDatagramRelayAuthTicket",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CMsgSteamDatagramRelayAuthTicket {
        static instance: ::protobuf::rt::LazyV2<CMsgSteamDatagramRelayAuthTicket> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CMsgSteamDatagramRelayAuthTicket::new)
    }
}

impl ::protobuf::Clear for CMsgSteamDatagramRelayAuthTicket {
    fn clear(&mut self) {
        self.time_expiry = ::std::option::Option::None;
        self.authorized_steam_id = ::std::option::Option::None;
        self.authorized_public_ip = ::std::option::Option::None;
        self.gameserver_steam_id = ::std::option::Option::None;
        self.gameserver_net_id = ::std::option::Option::None;
        self.legacy_signature.clear();
        self.app_id = ::std::option::Option::None;
        self.gameserver_pop_id = ::std::option::Option::None;
        self.virtual_port = ::std::option::Option::None;
        self.extra_fields.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CMsgSteamDatagramRelayAuthTicket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramRelayAuthTicket {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CMsgSteamDatagramRelayAuthTicket_ExtraField {
    // message fields
    name: ::protobuf::SingularField<::std::string::String>,
    string_value: ::protobuf::SingularField<::std::string::String>,
    int64_value: ::std::option::Option<i64>,
    fixed64_value: ::std::option::Option<u64>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CMsgSteamDatagramRelayAuthTicket_ExtraField {
    fn default() -> &'a CMsgSteamDatagramRelayAuthTicket_ExtraField {
        <CMsgSteamDatagramRelayAuthTicket_ExtraField as ::protobuf::Message>::default_instance()
    }
}

impl CMsgSteamDatagramRelayAuthTicket_ExtraField {
    pub fn new() -> CMsgSteamDatagramRelayAuthTicket_ExtraField {
        ::std::default::Default::default()
    }

    // optional string name = 1;


    pub fn get_name(&self) -> &str {
        match self.name.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    pub fn has_name(&self) -> bool {
        self.name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        if self.name.is_none() {
            self.name.set_default();
        }
        self.name.as_mut().unwrap()
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        self.name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string string_value = 2;


    pub fn get_string_value(&self) -> &str {
        match self.string_value.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_string_value(&mut self) {
        self.string_value.clear();
    }

    pub fn has_string_value(&self) -> bool {
        self.string_value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_string_value(&mut self, v: ::std::string::String) {
        self.string_value = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_string_value(&mut self) -> &mut ::std::string::String {
        if self.string_value.is_none() {
            self.string_value.set_default();
        }
        self.string_value.as_mut().unwrap()
    }

    // Take field
    pub fn take_string_value(&mut self) -> ::std::string::String {
        self.string_value.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional sint64 int64_value = 3;


    pub fn get_int64_value(&self) -> i64 {
        self.int64_value.unwrap_or(0)
    }
    pub fn clear_int64_value(&mut self) {
        self.int64_value = ::std::option::Option::None;
    }

    pub fn has_int64_value(&self) -> bool {
        self.int64_value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_int64_value(&mut self, v: i64) {
        self.int64_value = ::std::option::Option::Some(v);
    }

    // optional fixed64 fixed64_value = 5;


    pub fn get_fixed64_value(&self) -> u64 {
        self.fixed64_value.unwrap_or(0)
    }
    pub fn clear_fixed64_value(&mut self) {
        self.fixed64_value = ::std::option::Option::None;
    }

    pub fn has_fixed64_value(&self) -> bool {
        self.fixed64_value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_fixed64_value(&mut self, v: u64) {
        self.fixed64_value = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for CMsgSteamDatagramRelayAuthTicket_ExtraField {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.string_value)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_sint64()?;
                    self.int64_value = ::std::option::Option::Some(tmp);
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.fixed64_value = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.string_value.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.int64_value {
            my_size += ::protobuf::rt::value_varint_zigzag_size(3, v);
        }
        if let Some(v) = self.fixed64_value {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.name.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.string_value.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(v) = self.int64_value {
            os.write_sint64(3, v)?;
        }
        if let Some(v) = self.fixed64_value {
            os.write_fixed64(5, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CMsgSteamDatagramRelayAuthTicket_ExtraField {
        CMsgSteamDatagramRelayAuthTicket_ExtraField::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &CMsgSteamDatagramRelayAuthTicket_ExtraField| { &m.name },
                |m: &mut CMsgSteamDatagramRelayAuthTicket_ExtraField| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "string_value",
                |m: &CMsgSteamDatagramRelayAuthTicket_ExtraField| { &m.string_value },
                |m: &mut CMsgSteamDatagramRelayAuthTicket_ExtraField| { &mut m.string_value },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeSint64>(
                "int64_value",
                |m: &CMsgSteamDatagramRelayAuthTicket_ExtraField| { &m.int64_value },
                |m: &mut CMsgSteamDatagramRelayAuthTicket_ExtraField| { &mut m.int64_value },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "fixed64_value",
                |m: &CMsgSteamDatagramRelayAuthTicket_ExtraField| { &m.fixed64_value },
                |m: &mut CMsgSteamDatagramRelayAuthTicket_ExtraField| { &mut m.fixed64_value },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CMsgSteamDatagramRelayAuthTicket_ExtraField>(
                "CMsgSteamDatagramRelayAuthTicket.ExtraField",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CMsgSteamDatagramRelayAuthTicket_ExtraField {
        static instance: ::protobuf::rt::LazyV2<CMsgSteamDatagramRelayAuthTicket_ExtraField> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CMsgSteamDatagramRelayAuthTicket_ExtraField::new)
    }
}

impl ::protobuf::Clear for CMsgSteamDatagramRelayAuthTicket_ExtraField {
    fn clear(&mut self) {
        self.name.clear();
        self.string_value.clear();
        self.int64_value = ::std::option::Option::None;
        self.fixed64_value = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CMsgSteamDatagramRelayAuthTicket_ExtraField {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramRelayAuthTicket_ExtraField {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CMsgSteamDatagramSignedRelayAuthTicket {
    // message fields
    reserved_do_not_use: ::std::option::Option<u64>,
    key_id: ::std::option::Option<u64>,
    ticket: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    signature: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CMsgSteamDatagramSignedRelayAuthTicket {
    fn default() -> &'a CMsgSteamDatagramSignedRelayAuthTicket {
        <CMsgSteamDatagramSignedRelayAuthTicket as ::protobuf::Message>::default_instance()
    }
}

impl CMsgSteamDatagramSignedRelayAuthTicket {
    pub fn new() -> CMsgSteamDatagramSignedRelayAuthTicket {
        ::std::default::Default::default()
    }

    // optional fixed64 reserved_do_not_use = 1;


    pub fn get_reserved_do_not_use(&self) -> u64 {
        self.reserved_do_not_use.unwrap_or(0)
    }
    pub fn clear_reserved_do_not_use(&mut self) {
        self.reserved_do_not_use = ::std::option::Option::None;
    }

    pub fn has_reserved_do_not_use(&self) -> bool {
        self.reserved_do_not_use.is_some()
    }

    // Param is passed by value, moved
    pub fn set_reserved_do_not_use(&mut self, v: u64) {
        self.reserved_do_not_use = ::std::option::Option::Some(v);
    }

    // optional fixed64 key_id = 2;


    pub fn get_key_id(&self) -> u64 {
        self.key_id.unwrap_or(0)
    }
    pub fn clear_key_id(&mut self) {
        self.key_id = ::std::option::Option::None;
    }

    pub fn has_key_id(&self) -> bool {
        self.key_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_key_id(&mut self, v: u64) {
        self.key_id = ::std::option::Option::Some(v);
    }

    // optional bytes ticket = 3;


    pub fn get_ticket(&self) -> &[u8] {
        match self.ticket.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_ticket(&mut self) {
        self.ticket.clear();
    }

    pub fn has_ticket(&self) -> bool {
        self.ticket.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ticket(&mut self, v: ::std::vec::Vec<u8>) {
        self.ticket = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ticket(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.ticket.is_none() {
            self.ticket.set_default();
        }
        self.ticket.as_mut().unwrap()
    }

    // Take field
    pub fn take_ticket(&mut self) -> ::std::vec::Vec<u8> {
        self.ticket.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional bytes signature = 4;


    pub fn get_signature(&self) -> &[u8] {
        match self.signature.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_signature(&mut self) {
        self.signature.clear();
    }

    pub fn has_signature(&self) -> bool {
        self.signature.is_some()
    }

    // Param is passed by value, moved
    pub fn set_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.signature = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.signature.is_none() {
            self.signature.set_default();
        }
        self.signature.as_mut().unwrap()
    }

    // Take field
    pub fn take_signature(&mut self) -> ::std::vec::Vec<u8> {
        self.signature.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for CMsgSteamDatagramSignedRelayAuthTicket {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.reserved_do_not_use = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.key_id = ::std::option::Option::Some(tmp);
                },
                3 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.ticket)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.signature)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.reserved_do_not_use {
            my_size += 9;
        }
        if let Some(v) = self.key_id {
            my_size += 9;
        }
        if let Some(ref v) = self.ticket.as_ref() {
            my_size += ::protobuf::rt::bytes_size(3, &v);
        }
        if let Some(ref v) = self.signature.as_ref() {
            my_size += ::protobuf::rt::bytes_size(4, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.reserved_do_not_use {
            os.write_fixed64(1, v)?;
        }
        if let Some(v) = self.key_id {
            os.write_fixed64(2, v)?;
        }
        if let Some(ref v) = self.ticket.as_ref() {
            os.write_bytes(3, &v)?;
        }
        if let Some(ref v) = self.signature.as_ref() {
            os.write_bytes(4, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CMsgSteamDatagramSignedRelayAuthTicket {
        CMsgSteamDatagramSignedRelayAuthTicket::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "reserved_do_not_use",
                |m: &CMsgSteamDatagramSignedRelayAuthTicket| { &m.reserved_do_not_use },
                |m: &mut CMsgSteamDatagramSignedRelayAuthTicket| { &mut m.reserved_do_not_use },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "key_id",
                |m: &CMsgSteamDatagramSignedRelayAuthTicket| { &m.key_id },
                |m: &mut CMsgSteamDatagramSignedRelayAuthTicket| { &mut m.key_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "ticket",
                |m: &CMsgSteamDatagramSignedRelayAuthTicket| { &m.ticket },
                |m: &mut CMsgSteamDatagramSignedRelayAuthTicket| { &mut m.ticket },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "signature",
                |m: &CMsgSteamDatagramSignedRelayAuthTicket| { &m.signature },
                |m: &mut CMsgSteamDatagramSignedRelayAuthTicket| { &mut m.signature },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CMsgSteamDatagramSignedRelayAuthTicket>(
                "CMsgSteamDatagramSignedRelayAuthTicket",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CMsgSteamDatagramSignedRelayAuthTicket {
        static instance: ::protobuf::rt::LazyV2<CMsgSteamDatagramSignedRelayAuthTicket> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CMsgSteamDatagramSignedRelayAuthTicket::new)
    }
}

impl ::protobuf::Clear for CMsgSteamDatagramSignedRelayAuthTicket {
    fn clear(&mut self) {
        self.reserved_do_not_use = ::std::option::Option::None;
        self.key_id = ::std::option::Option::None;
        self.ticket.clear();
        self.signature.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CMsgSteamDatagramSignedRelayAuthTicket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramSignedRelayAuthTicket {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CMsgSteamDatagramCertificate {
    // message fields
    key_type: ::std::option::Option<CMsgSteamDatagramCertificate_EKeyType>,
    key_data: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    steam_id: ::std::option::Option<u64>,
    pub gameserver_datacenter_ids: ::std::vec::Vec<u32>,
    time_created: ::std::option::Option<u32>,
    time_expiry: ::std::option::Option<u32>,
    app_id: ::std::option::Option<u32>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CMsgSteamDatagramCertificate {
    fn default() -> &'a CMsgSteamDatagramCertificate {
        <CMsgSteamDatagramCertificate as ::protobuf::Message>::default_instance()
    }
}

impl CMsgSteamDatagramCertificate {
    pub fn new() -> CMsgSteamDatagramCertificate {
        ::std::default::Default::default()
    }

    // optional .CMsgSteamDatagramCertificate.EKeyType key_type = 1;


    pub fn get_key_type(&self) -> CMsgSteamDatagramCertificate_EKeyType {
        self.key_type.unwrap_or(CMsgSteamDatagramCertificate_EKeyType::INVALID)
    }
    pub fn clear_key_type(&mut self) {
        self.key_type = ::std::option::Option::None;
    }

    pub fn has_key_type(&self) -> bool {
        self.key_type.is_some()
    }

    // Param is passed by value, moved
    pub fn set_key_type(&mut self, v: CMsgSteamDatagramCertificate_EKeyType) {
        self.key_type = ::std::option::Option::Some(v);
    }

    // optional bytes key_data = 2;


    pub fn get_key_data(&self) -> &[u8] {
        match self.key_data.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_key_data(&mut self) {
        self.key_data.clear();
    }

    pub fn has_key_data(&self) -> bool {
        self.key_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_key_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.key_data = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.key_data.is_none() {
            self.key_data.set_default();
        }
        self.key_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_key_data(&mut self) -> ::std::vec::Vec<u8> {
        self.key_data.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional fixed64 steam_id = 4;


    pub fn get_steam_id(&self) -> u64 {
        self.steam_id.unwrap_or(0)
    }
    pub fn clear_steam_id(&mut self) {
        self.steam_id = ::std::option::Option::None;
    }

    pub fn has_steam_id(&self) -> bool {
        self.steam_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_steam_id(&mut self, v: u64) {
        self.steam_id = ::std::option::Option::Some(v);
    }

    // repeated fixed32 gameserver_datacenter_ids = 5;


    pub fn get_gameserver_datacenter_ids(&self) -> &[u32] {
        &self.gameserver_datacenter_ids
    }
    pub fn clear_gameserver_datacenter_ids(&mut self) {
        self.gameserver_datacenter_ids.clear();
    }

    // Param is passed by value, moved
    pub fn set_gameserver_datacenter_ids(&mut self, v: ::std::vec::Vec<u32>) {
        self.gameserver_datacenter_ids = v;
    }

    // Mutable pointer to the field.
    pub fn mut_gameserver_datacenter_ids(&mut self) -> &mut ::std::vec::Vec<u32> {
        &mut self.gameserver_datacenter_ids
    }

    // Take field
    pub fn take_gameserver_datacenter_ids(&mut self) -> ::std::vec::Vec<u32> {
        ::std::mem::replace(&mut self.gameserver_datacenter_ids, ::std::vec::Vec::new())
    }

    // optional fixed32 time_created = 8;


    pub fn get_time_created(&self) -> u32 {
        self.time_created.unwrap_or(0)
    }
    pub fn clear_time_created(&mut self) {
        self.time_created = ::std::option::Option::None;
    }

    pub fn has_time_created(&self) -> bool {
        self.time_created.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_created(&mut self, v: u32) {
        self.time_created = ::std::option::Option::Some(v);
    }

    // optional fixed32 time_expiry = 9;


    pub fn get_time_expiry(&self) -> u32 {
        self.time_expiry.unwrap_or(0)
    }
    pub fn clear_time_expiry(&mut self) {
        self.time_expiry = ::std::option::Option::None;
    }

    pub fn has_time_expiry(&self) -> bool {
        self.time_expiry.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_expiry(&mut self, v: u32) {
        self.time_expiry = ::std::option::Option::Some(v);
    }

    // optional uint32 app_id = 10;


    pub fn get_app_id(&self) -> u32 {
        self.app_id.unwrap_or(0)
    }
    pub fn clear_app_id(&mut self) {
        self.app_id = ::std::option::Option::None;
    }

    pub fn has_app_id(&self) -> bool {
        self.app_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_app_id(&mut self, v: u32) {
        self.app_id = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for CMsgSteamDatagramCertificate {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto2_enum_with_unknown_fields_into(wire_type, is, &mut self.key_type, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.key_data)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.steam_id = ::std::option::Option::Some(tmp);
                },
                5 => {
                    ::protobuf::rt::read_repeated_fixed32_into(wire_type, is, &mut self.gameserver_datacenter_ids)?;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed32()?;
                    self.time_created = ::std::option::Option::Some(tmp);
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed32()?;
                    self.time_expiry = ::std::option::Option::Some(tmp);
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.app_id = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.key_type {
            my_size += ::protobuf::rt::enum_size(1, v);
        }
        if let Some(ref v) = self.key_data.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        if let Some(v) = self.steam_id {
            my_size += 9;
        }
        my_size += 5 * self.gameserver_datacenter_ids.len() as u32;
        if let Some(v) = self.time_created {
            my_size += 5;
        }
        if let Some(v) = self.time_expiry {
            my_size += 5;
        }
        if let Some(v) = self.app_id {
            my_size += ::protobuf::rt::value_size(10, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.key_type {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&v))?;
        }
        if let Some(ref v) = self.key_data.as_ref() {
            os.write_bytes(2, &v)?;
        }
        if let Some(v) = self.steam_id {
            os.write_fixed64(4, v)?;
        }
        for v in &self.gameserver_datacenter_ids {
            os.write_fixed32(5, *v)?;
        };
        if let Some(v) = self.time_created {
            os.write_fixed32(8, v)?;
        }
        if let Some(v) = self.time_expiry {
            os.write_fixed32(9, v)?;
        }
        if let Some(v) = self.app_id {
            os.write_uint32(10, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CMsgSteamDatagramCertificate {
        CMsgSteamDatagramCertificate::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeEnum<CMsgSteamDatagramCertificate_EKeyType>>(
                "key_type",
                |m: &CMsgSteamDatagramCertificate| { &m.key_type },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.key_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "key_data",
                |m: &CMsgSteamDatagramCertificate| { &m.key_data },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.key_data },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "steam_id",
                |m: &CMsgSteamDatagramCertificate| { &m.steam_id },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.steam_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "gameserver_datacenter_ids",
                |m: &CMsgSteamDatagramCertificate| { &m.gameserver_datacenter_ids },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.gameserver_datacenter_ids },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "time_created",
                |m: &CMsgSteamDatagramCertificate| { &m.time_created },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.time_created },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed32>(
                "time_expiry",
                |m: &CMsgSteamDatagramCertificate| { &m.time_expiry },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.time_expiry },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "app_id",
                |m: &CMsgSteamDatagramCertificate| { &m.app_id },
                |m: &mut CMsgSteamDatagramCertificate| { &mut m.app_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CMsgSteamDatagramCertificate>(
                "CMsgSteamDatagramCertificate",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CMsgSteamDatagramCertificate {
        static instance: ::protobuf::rt::LazyV2<CMsgSteamDatagramCertificate> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CMsgSteamDatagramCertificate::new)
    }
}

impl ::protobuf::Clear for CMsgSteamDatagramCertificate {
    fn clear(&mut self) {
        self.key_type = ::std::option::Option::None;
        self.key_data.clear();
        self.steam_id = ::std::option::Option::None;
        self.gameserver_datacenter_ids.clear();
        self.time_created = ::std::option::Option::None;
        self.time_expiry = ::std::option::Option::None;
        self.app_id = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CMsgSteamDatagramCertificate {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramCertificate {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum CMsgSteamDatagramCertificate_EKeyType {
    INVALID = 0,
    ED25519 = 1,
}

impl ::protobuf::ProtobufEnum for CMsgSteamDatagramCertificate_EKeyType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CMsgSteamDatagramCertificate_EKeyType> {
        match value {
            0 => ::std::option::Option::Some(CMsgSteamDatagramCertificate_EKeyType::INVALID),
            1 => ::std::option::Option::Some(CMsgSteamDatagramCertificate_EKeyType::ED25519),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [CMsgSteamDatagramCertificate_EKeyType] = &[
            CMsgSteamDatagramCertificate_EKeyType::INVALID,
            CMsgSteamDatagramCertificate_EKeyType::ED25519,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<CMsgSteamDatagramCertificate_EKeyType>("CMsgSteamDatagramCertificate.EKeyType", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for CMsgSteamDatagramCertificate_EKeyType {
}

impl ::std::default::Default for CMsgSteamDatagramCertificate_EKeyType {
    fn default() -> Self {
        CMsgSteamDatagramCertificate_EKeyType::INVALID
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramCertificate_EKeyType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CMsgSteamDatagramCertificateSigned {
    // message fields
    cert: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    ca_key_id: ::std::option::Option<u64>,
    ca_signature: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CMsgSteamDatagramCertificateSigned {
    fn default() -> &'a CMsgSteamDatagramCertificateSigned {
        <CMsgSteamDatagramCertificateSigned as ::protobuf::Message>::default_instance()
    }
}

impl CMsgSteamDatagramCertificateSigned {
    pub fn new() -> CMsgSteamDatagramCertificateSigned {
        ::std::default::Default::default()
    }

    // optional bytes cert = 4;


    pub fn get_cert(&self) -> &[u8] {
        match self.cert.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_cert(&mut self) {
        self.cert.clear();
    }

    pub fn has_cert(&self) -> bool {
        self.cert.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cert(&mut self, v: ::std::vec::Vec<u8>) {
        self.cert = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cert(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.cert.is_none() {
            self.cert.set_default();
        }
        self.cert.as_mut().unwrap()
    }

    // Take field
    pub fn take_cert(&mut self) -> ::std::vec::Vec<u8> {
        self.cert.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional fixed64 ca_key_id = 5;


    pub fn get_ca_key_id(&self) -> u64 {
        self.ca_key_id.unwrap_or(0)
    }
    pub fn clear_ca_key_id(&mut self) {
        self.ca_key_id = ::std::option::Option::None;
    }

    pub fn has_ca_key_id(&self) -> bool {
        self.ca_key_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ca_key_id(&mut self, v: u64) {
        self.ca_key_id = ::std::option::Option::Some(v);
    }

    // optional bytes ca_signature = 6;


    pub fn get_ca_signature(&self) -> &[u8] {
        match self.ca_signature.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_ca_signature(&mut self) {
        self.ca_signature.clear();
    }

    pub fn has_ca_signature(&self) -> bool {
        self.ca_signature.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ca_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.ca_signature = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ca_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.ca_signature.is_none() {
            self.ca_signature.set_default();
        }
        self.ca_signature.as_mut().unwrap()
    }

    // Take field
    pub fn take_ca_signature(&mut self) -> ::std::vec::Vec<u8> {
        self.ca_signature.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for CMsgSteamDatagramCertificateSigned {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                4 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.cert)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_fixed64()?;
                    self.ca_key_id = ::std::option::Option::Some(tmp);
                },
                6 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.ca_signature)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.cert.as_ref() {
            my_size += ::protobuf::rt::bytes_size(4, &v);
        }
        if let Some(v) = self.ca_key_id {
            my_size += 9;
        }
        if let Some(ref v) = self.ca_signature.as_ref() {
            my_size += ::protobuf::rt::bytes_size(6, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.cert.as_ref() {
            os.write_bytes(4, &v)?;
        }
        if let Some(v) = self.ca_key_id {
            os.write_fixed64(5, v)?;
        }
        if let Some(ref v) = self.ca_signature.as_ref() {
            os.write_bytes(6, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CMsgSteamDatagramCertificateSigned {
        CMsgSteamDatagramCertificateSigned::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "cert",
                |m: &CMsgSteamDatagramCertificateSigned| { &m.cert },
                |m: &mut CMsgSteamDatagramCertificateSigned| { &mut m.cert },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeFixed64>(
                "ca_key_id",
                |m: &CMsgSteamDatagramCertificateSigned| { &m.ca_key_id },
                |m: &mut CMsgSteamDatagramCertificateSigned| { &mut m.ca_key_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "ca_signature",
                |m: &CMsgSteamDatagramCertificateSigned| { &m.ca_signature },
                |m: &mut CMsgSteamDatagramCertificateSigned| { &mut m.ca_signature },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CMsgSteamDatagramCertificateSigned>(
                "CMsgSteamDatagramCertificateSigned",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CMsgSteamDatagramCertificateSigned {
        static instance: ::protobuf::rt::LazyV2<CMsgSteamDatagramCertificateSigned> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CMsgSteamDatagramCertificateSigned::new)
    }
}

impl ::protobuf::Clear for CMsgSteamDatagramCertificateSigned {
    fn clear(&mut self) {
        self.cert.clear();
        self.ca_key_id = ::std::option::Option::None;
        self.ca_signature.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CMsgSteamDatagramCertificateSigned {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CMsgSteamDatagramCertificateSigned {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n!steamdatagram_auth_messages.proto\"\xef\x04\n\x20CMsgSteamDatagramRel\
    ayAuthTicket\x12\x1f\n\x0btime_expiry\x18\x01\x20\x01(\x07R\ntimeExpiry\
    \x12.\n\x13authorized_steam_id\x18\x02\x20\x01(\x06R\x11authorizedSteamI\
    d\x120\n\x14authorized_public_ip\x18\x03\x20\x01(\x07R\x12authorizedPubl\
    icIp\x12.\n\x13gameserver_steam_id\x18\x04\x20\x01(\x06R\x11gameserverSt\
    eamId\x12*\n\x11gameserver_net_id\x18\x05\x20\x01(\x06R\x0fgameserverNet\
    Id\x12)\n\x10legacy_signature\x18\x06\x20\x01(\x0cR\x0flegacySignature\
    \x12\x15\n\x06app_id\x18\x07\x20\x01(\rR\x05appId\x12*\n\x11gameserver_p\
    op_id\x18\t\x20\x01(\x07R\x0fgameserverPopId\x12!\n\x0cvirtual_port\x18\
    \n\x20\x01(\rR\x0bvirtualPort\x12O\n\x0cextra_fields\x18\x08\x20\x03(\
    \x0b2,.CMsgSteamDatagramRelayAuthTicket.ExtraFieldR\x0bextraFields\x1a\
    \x89\x01\n\nExtraField\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12\
    !\n\x0cstring_value\x18\x02\x20\x01(\tR\x0bstringValue\x12\x1f\n\x0bint6\
    4_value\x18\x03\x20\x01(\x12R\nint64Value\x12#\n\rfixed64_value\x18\x05\
    \x20\x01(\x06R\x0cfixed64Value\"\xa4\x01\n&CMsgSteamDatagramSignedRelayA\
    uthTicket\x12-\n\x13reserved_do_not_use\x18\x01\x20\x01(\x06R\x10reserve\
    dDoNotUse\x12\x15\n\x06key_id\x18\x02\x20\x01(\x06R\x05keyId\x12\x16\n\
    \x06ticket\x18\x03\x20\x01(\x0cR\x06ticket\x12\x1c\n\tsignature\x18\x04\
    \x20\x01(\x0cR\tsignature\"\xdd\x02\n\x1cCMsgSteamDatagramCertificate\
    \x12J\n\x08key_type\x18\x01\x20\x01(\x0e2&.CMsgSteamDatagramCertificate.\
    EKeyType:\x07INVALIDR\x07keyType\x12\x19\n\x08key_data\x18\x02\x20\x01(\
    \x0cR\x07keyData\x12\x19\n\x08steam_id\x18\x04\x20\x01(\x06R\x07steamId\
    \x12:\n\x19gameserver_datacenter_ids\x18\x05\x20\x03(\x07R\x17gameserver\
    DatacenterIds\x12!\n\x0ctime_created\x18\x08\x20\x01(\x07R\x0btimeCreate\
    d\x12\x1f\n\x0btime_expiry\x18\t\x20\x01(\x07R\ntimeExpiry\x12\x15\n\x06\
    app_id\x18\n\x20\x01(\rR\x05appId\"$\n\x08EKeyType\x12\x0b\n\x07INVALID\
    \x10\0\x12\x0b\n\x07ED25519\x10\x01\"w\n\"CMsgSteamDatagramCertificateSi\
    gned\x12\x12\n\x04cert\x18\x04\x20\x01(\x0cR\x04cert\x12\x1a\n\tca_key_i\
    d\x18\x05\x20\x01(\x06R\x07caKeyId\x12!\n\x0cca_signature\x18\x06\x20\
    \x01(\x0cR\x0bcaSignatureB\x03\x80\x01\0J\xe3\x11\n\x06\x12\x04\0\00\x01\
    \n\x08\n\x01\x08\x12\x03\0\0#\n\t\n\x02\x08\x10\x12\x03\0\0#\n\n\n\x02\
    \x04\0\x12\x04\x02\0\x14\x01\n\n\n\x03\x04\0\x01\x12\x03\x02\x08(\n\x0c\
    \n\x04\x04\0\x03\0\x12\x04\x03\x08\x08\t\n\x0c\n\x05\x04\0\x03\0\x01\x12\
    \x03\x03\x10\x1a\n\r\n\x06\x04\0\x03\0\x02\0\x12\x03\x04\x10)\n\x0e\n\
    \x07\x04\0\x03\0\x02\0\x04\x12\x03\x04\x10\x18\n\x0e\n\x07\x04\0\x03\0\
    \x02\0\x05\x12\x03\x04\x19\x1f\n\x0e\n\x07\x04\0\x03\0\x02\0\x01\x12\x03\
    \x04\x20$\n\x0e\n\x07\x04\0\x03\0\x02\0\x03\x12\x03\x04'(\n\r\n\x06\x04\
    \0\x03\0\x02\x01\x12\x03\x05\x101\n\x0e\n\x07\x04\0\x03\0\x02\x01\x04\
    \x12\x03\x05\x10\x18\n\x0e\n\x07\x04\0\x03\0\x02\x01\x05\x12\x03\x05\x19\
    \x1f\n\x0e\n\x07\x04\0\x03\0\x02\x01\x01\x12\x03\x05\x20,\n\x0e\n\x07\
    \x04\0\x03\0\x02\x01\x03\x12\x03\x05/0\n\r\n\x06\x04\0\x03\0\x02\x02\x12\
    \x03\x06\x100\n\x0e\n\x07\x04\0\x03\0\x02\x02\x04\x12\x03\x06\x10\x18\n\
    \x0e\n\x07\x04\0\x03\0\x02\x02\x05\x12\x03\x06\x19\x1f\n\x0e\n\x07\x04\0\
    \x03\0\x02\x02\x01\x12\x03\x06\x20+\n\x0e\n\x07\x04\0\x03\0\x02\x02\x03\
    \x12\x03\x06./\n\r\n\x06\x04\0\x03\0\x02\x03\x12\x03\x07\x103\n\x0e\n\
    \x07\x04\0\x03\0\x02\x03\x04\x12\x03\x07\x10\x18\n\x0e\n\x07\x04\0\x03\0\
    \x02\x03\x05\x12\x03\x07\x19\x20\n\x0e\n\x07\x04\0\x03\0\x02\x03\x01\x12\
    \x03\x07!.\n\x0e\n\x07\x04\0\x03\0\x02\x03\x03\x12\x03\x0712\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\n\x08)\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\n\x08\
    \x10\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\n\x11\x18\n\x0c\n\x05\x04\0\x02\
    \0\x01\x12\x03\n\x19$\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\n'(\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x0b\x081\n\x0c\n\x05\x04\0\x02\x01\x04\x12\
    \x03\x0b\x08\x10\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0b\x11\x18\n\x0c\
    \n\x05\x04\0\x02\x01\x01\x12\x03\x0b\x19,\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x0b/0\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0c\x082\n\x0c\n\x05\
    \x04\0\x02\x02\x04\x12\x03\x0c\x08\x10\n\x0c\n\x05\x04\0\x02\x02\x05\x12\
    \x03\x0c\x11\x18\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0c\x19-\n\x0c\n\
    \x05\x04\0\x02\x02\x03\x12\x03\x0c01\n\x0b\n\x04\x04\0\x02\x03\x12\x03\r\
    \x081\n\x0c\n\x05\x04\0\x02\x03\x04\x12\x03\r\x08\x10\n\x0c\n\x05\x04\0\
    \x02\x03\x05\x12\x03\r\x11\x18\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\r\
    \x19,\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\r/0\n\x0b\n\x04\x04\0\x02\
    \x04\x12\x03\x0e\x08/\n\x0c\n\x05\x04\0\x02\x04\x04\x12\x03\x0e\x08\x10\
    \n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x0e\x11\x18\n\x0c\n\x05\x04\0\x02\
    \x04\x01\x12\x03\x0e\x19*\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x0e-.\n\
    \x0b\n\x04\x04\0\x02\x05\x12\x03\x0f\x08,\n\x0c\n\x05\x04\0\x02\x05\x04\
    \x12\x03\x0f\x08\x10\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x0f\x11\x16\n\
    \x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x0f\x17'\n\x0c\n\x05\x04\0\x02\x05\
    \x03\x12\x03\x0f*+\n\x0b\n\x04\x04\0\x02\x06\x12\x03\x10\x08#\n\x0c\n\
    \x05\x04\0\x02\x06\x04\x12\x03\x10\x08\x10\n\x0c\n\x05\x04\0\x02\x06\x05\
    \x12\x03\x10\x11\x17\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\x10\x18\x1e\n\
    \x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x10!\"\n\x0b\n\x04\x04\0\x02\x07\
    \x12\x03\x11\x08/\n\x0c\n\x05\x04\0\x02\x07\x04\x12\x03\x11\x08\x10\n\
    \x0c\n\x05\x04\0\x02\x07\x05\x12\x03\x11\x11\x18\n\x0c\n\x05\x04\0\x02\
    \x07\x01\x12\x03\x11\x19*\n\x0c\n\x05\x04\0\x02\x07\x03\x12\x03\x11-.\n\
    \x0b\n\x04\x04\0\x02\x08\x12\x03\x12\x08*\n\x0c\n\x05\x04\0\x02\x08\x04\
    \x12\x03\x12\x08\x10\n\x0c\n\x05\x04\0\x02\x08\x05\x12\x03\x12\x11\x17\n\
    \x0c\n\x05\x04\0\x02\x08\x01\x12\x03\x12\x18$\n\x0c\n\x05\x04\0\x02\x08\
    \x03\x12\x03\x12')\n\x0b\n\x04\x04\0\x02\t\x12\x03\x13\x08O\n\x0c\n\x05\
    \x04\0\x02\t\x04\x12\x03\x13\x08\x10\n\x0c\n\x05\x04\0\x02\t\x06\x12\x03\
    \x13\x11=\n\x0c\n\x05\x04\0\x02\t\x01\x12\x03\x13>J\n\x0c\n\x05\x04\0\
    \x02\t\x03\x12\x03\x13MN\n\n\n\x02\x04\x01\x12\x04\x16\0\x1b\x01\n\n\n\
    \x03\x04\x01\x01\x12\x03\x16\x08.\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x17\
    \x081\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03\x17\x08\x10\n\x0c\n\x05\x04\
    \x01\x02\0\x05\x12\x03\x17\x11\x18\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\
    \x17\x19,\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x17/0\n\x0b\n\x04\x04\
    \x01\x02\x01\x12\x03\x18\x08$\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x03\
    \x18\x08\x10\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x18\x11\x18\n\x0c\n\
    \x05\x04\x01\x02\x01\x01\x12\x03\x18\x19\x1f\n\x0c\n\x05\x04\x01\x02\x01\
    \x03\x12\x03\x18\"#\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\x19\x08\"\n\x0c\
    \n\x05\x04\x01\x02\x02\x04\x12\x03\x19\x08\x10\n\x0c\n\x05\x04\x01\x02\
    \x02\x05\x12\x03\x19\x11\x16\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x19\
    \x17\x1d\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x19\x20!\n\x0b\n\x04\
    \x04\x01\x02\x03\x12\x03\x1a\x08%\n\x0c\n\x05\x04\x01\x02\x03\x04\x12\
    \x03\x1a\x08\x10\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\x1a\x11\x16\n\
    \x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x1a\x17\x20\n\x0c\n\x05\x04\x01\
    \x02\x03\x03\x12\x03\x1a#$\n\n\n\x02\x04\x02\x12\x04\x1d\0*\x01\n\n\n\
    \x03\x04\x02\x01\x12\x03\x1d\x08$\n\x0c\n\x04\x04\x02\x04\0\x12\x04\x1e\
    \x08!\t\n\x0c\n\x05\x04\x02\x04\0\x01\x12\x03\x1e\r\x15\n\r\n\x06\x04\
    \x02\x04\0\x02\0\x12\x03\x1f\x10\x1c\n\x0e\n\x07\x04\x02\x04\0\x02\0\x01\
    \x12\x03\x1f\x10\x17\n\x0e\n\x07\x04\x02\x04\0\x02\0\x02\x12\x03\x1f\x1a\
    \x1b\n\r\n\x06\x04\x02\x04\0\x02\x01\x12\x03\x20\x10\x1c\n\x0e\n\x07\x04\
    \x02\x04\0\x02\x01\x01\x12\x03\x20\x10\x17\n\x0e\n\x07\x04\x02\x04\0\x02\
    \x01\x02\x12\x03\x20\x1a\x1b\n\x0b\n\x04\x04\x02\x02\0\x12\x03#\x08Y\n\
    \x0c\n\x05\x04\x02\x02\0\x04\x12\x03#\x08\x10\n\x0c\n\x05\x04\x02\x02\0\
    \x06\x12\x03#\x117\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03#8@\n\x0c\n\x05\
    \x04\x02\x02\0\x03\x12\x03#CD\n\x0c\n\x05\x04\x02\x02\0\x08\x12\x03#EX\n\
    \x0c\n\x05\x04\x02\x02\0\x07\x12\x03#PW\n\x0b\n\x04\x04\x02\x02\x01\x12\
    \x03$\x08$\n\x0c\n\x05\x04\x02\x02\x01\x04\x12\x03$\x08\x10\n\x0c\n\x05\
    \x04\x02\x02\x01\x05\x12\x03$\x11\x16\n\x0c\n\x05\x04\x02\x02\x01\x01\
    \x12\x03$\x17\x1f\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03$\"#\n\x0b\n\
    \x04\x04\x02\x02\x02\x12\x03%\x08&\n\x0c\n\x05\x04\x02\x02\x02\x04\x12\
    \x03%\x08\x10\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x03%\x11\x18\n\x0c\n\
    \x05\x04\x02\x02\x02\x01\x12\x03%\x19!\n\x0c\n\x05\x04\x02\x02\x02\x03\
    \x12\x03%$%\n\x0b\n\x04\x04\x02\x02\x03\x12\x03&\x087\n\x0c\n\x05\x04\
    \x02\x02\x03\x04\x12\x03&\x08\x10\n\x0c\n\x05\x04\x02\x02\x03\x05\x12\
    \x03&\x11\x18\n\x0c\n\x05\x04\x02\x02\x03\x01\x12\x03&\x192\n\x0c\n\x05\
    \x04\x02\x02\x03\x03\x12\x03&56\n\x0b\n\x04\x04\x02\x02\x04\x12\x03'\x08\
    *\n\x0c\n\x05\x04\x02\x02\x04\x04\x12\x03'\x08\x10\n\x0c\n\x05\x04\x02\
    \x02\x04\x05\x12\x03'\x11\x18\n\x0c\n\x05\x04\x02\x02\x04\x01\x12\x03'\
    \x19%\n\x0c\n\x05\x04\x02\x02\x04\x03\x12\x03'()\n\x0b\n\x04\x04\x02\x02\
    \x05\x12\x03(\x08)\n\x0c\n\x05\x04\x02\x02\x05\x04\x12\x03(\x08\x10\n\
    \x0c\n\x05\x04\x02\x02\x05\x05\x12\x03(\x11\x18\n\x0c\n\x05\x04\x02\x02\
    \x05\x01\x12\x03(\x19$\n\x0c\n\x05\x04\x02\x02\x05\x03\x12\x03('(\n\x0b\
    \n\x04\x04\x02\x02\x06\x12\x03)\x08$\n\x0c\n\x05\x04\x02\x02\x06\x04\x12\
    \x03)\x08\x10\n\x0c\n\x05\x04\x02\x02\x06\x05\x12\x03)\x11\x17\n\x0c\n\
    \x05\x04\x02\x02\x06\x01\x12\x03)\x18\x1e\n\x0c\n\x05\x04\x02\x02\x06\
    \x03\x12\x03)!#\n\n\n\x02\x04\x03\x12\x04,\00\x01\n\n\n\x03\x04\x03\x01\
    \x12\x03,\x08*\n\x0b\n\x04\x04\x03\x02\0\x12\x03-\x08\x20\n\x0c\n\x05\
    \x04\x03\x02\0\x04\x12\x03-\x08\x10\n\x0c\n\x05\x04\x03\x02\0\x05\x12\
    \x03-\x11\x16\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03-\x17\x1b\n\x0c\n\x05\
    \x04\x03\x02\0\x03\x12\x03-\x1e\x1f\n\x0b\n\x04\x04\x03\x02\x01\x12\x03.\
    \x08'\n\x0c\n\x05\x04\x03\x02\x01\x04\x12\x03.\x08\x10\n\x0c\n\x05\x04\
    \x03\x02\x01\x05\x12\x03.\x11\x18\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\
    \x03.\x19\"\n\x0c\n\x05\x04\x03\x02\x01\x03\x12\x03.%&\n\x0b\n\x04\x04\
    \x03\x02\x02\x12\x03/\x08(\n\x0c\n\x05\x04\x03\x02\x02\x04\x12\x03/\x08\
    \x10\n\x0c\n\x05\x04\x03\x02\x02\x05\x12\x03/\x11\x16\n\x0c\n\x05\x04\
    \x03\x02\x02\x01\x12\x03/\x17#\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03/&\
    '\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
